server:
    port: 8080
    servlet:
        context-path: /ficai

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create