name: CI/CD for Spring Boot

on:
  push:
    branches:
      - main  
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Change to your desired Java version
        distribution: 'temurin'
        
    - name: Grant execute permission to mvnw
      run: chmod +x mvnw
      
    - name: Build the Spring Boot application
      run: |
        sudo ./mvnw clean install -DskipTests=true

    - name: Run automated tests
      run: |
        ./mvnw test

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: spring-boot-artifacts
        path: target/*.jar  # Modify the path based on your build output
